cleaning_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 20.0
   publish_frequency: 20.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1
   inflation_radius: 0.25
   map_type: costmap

#Setup distance between cleaning lines
cleaning_plan_nodehandle:   
   size_of_cell: 7
   grid_covered_value: 200
